server:
  port: 8189
  servlet:
    context-path: /planner
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./backend/src/main/resources/db/net/tasks_db;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  flyway:
    enabled: true
